# Generated by Django 6.0.3 on 2026-03-25 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registereduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=50)),
                ('speed', models.CharField(blank=True, max_length=20, null=True)),
                ('plate_number', models.CharField(max_length=20)),
                ('frame_time', models.CharField(max_length=20)),
                ('severity', models.CharField(max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='app.registereduser')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
